import { checkHeadline } from './src/scorer.js';

// ─── Known AI-generation domains → instant flag ───────────────────────────────
const AI_DOMAINS = [
  'artbreeder.com','thispersondoesnotexist.com','generated.photos',
  'nightcafe.studio','midjourney.com','lexica.art','dreamstudio.ai',
  'civitai.com','playground.ai','seaart.ai','tensor.art','runwayml.com',
  'thiswaifudoesnotexist.com','thiscatdoesnotexist.com',
];

// URL-level hints (matched against image src)
const AI_URL_PATTERNS = [
  'midjourney','dall-e','dalle','stable-diffusion','stablediffusion',
  'ai-generated','ai_generated','deepfake','artbreeder','nightcafe',
  'generated-photo','synthetic','gan-face',
];

// Caption/context text hints (matched against surrounding page text & alt text)
const AI_TEXT_PATTERNS = [
  'ai art', 'ai image', 'ai generated', 'ai-generated',
  'artificial intelligence art', 'artificial intelligence image',
  'generative art', 'generated art', 'generated by ai',
  'made by ai', 'created by ai', 'created with ai',
  'midjourney', 'dall-e', 'dalle', 'stable diffusion',
  'stable-diffusion', 'deepfake', 'adobe firefly', 'nightcafe',
  'ai artwork', 'neural network art', 'synthetic image',
  'image generation', 'text to image', 'text-to-image',
];

function quickScore(hostname, src, contextStr) {
  // 1. Exact domain match → instant 95%
  if (hostname && AI_DOMAINS.some(d => hostname.includes(d))) return 0.95;

  const urlLower = (src || '').toLowerCase();
  const txtLower = (contextStr || '').toLowerCase();

  // 2. URL keyword match → 85%
  if (AI_URL_PATTERNS.some(p => urlLower.includes(p))) return 0.85;

  // 3. Caption / surrounding text keyword match → 82%
  //    (catches articles about AI art where the image IS the AI art being discussed)
  if (AI_TEXT_PATTERNS.some(p => txtLower.includes(p))) {
    console.log('[TruthLens] Context keyword hit in surrounding text');
    return 0.82;
  }

  return 0;
}

// ─── Stats ────────────────────────────────────────────────────────────────────
async function getStats() {
  return new Promise(r => chrome.storage.local.get({ imagesScanned: 0, deepfakesDetected: 0 }, r));
}
async function bumpStats(isFake) {
  const s = await getStats();
  chrome.storage.local.set({ imagesScanned: s.imagesScanned + 1, deepfakesDetected: s.deepfakesDetected + (isFake ? 1 : 0) });
}

// ─── Message router ───────────────────────────────────────────────────────────
chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  if (msg.type === 'ANALYZE')          { analyzeImageByUrl(msg.src, msg.hostname, msg.context).then(sendResponse); return true; }
  if (msg.type === 'ANALYZE_HEADLINE') { checkHeadline(msg.headline).then(sendResponse); return true; }
  if (msg.type === 'GET_STATS')        { getStats().then(sendResponse); return true; }
});

// ─── Digital Fingerprint Scanner (Metadata) ──────────────────────────────────
// Searches for "Smoking Gun" signatures hidden in image headers.
const AI_SIGNATURES = [
  'DALL-E', 'Midjourney', 'Adobe Firefly', 'Stable Diffusion', 
  'Civitai', 'DreamStudio', 'Generative AI', 'DeepAI'
];

async function checkMetadata(blob) {
  // Read first 4KB of binary data (where EXIF/Headers live)
  const head = await blob.slice(0, 4096).text();
  for (const sig of AI_SIGNATURES) {
    if (head.includes(sig)) return { found: true, name: sig };
  }
  return { found: false };
}

// ─── Main entry point ─────────────────────────────────────────────────────────
async function analyzeImageByUrl(url, hostname, contextStr) {
  // Fast-path #1: Known AI domain / URL / Caption Context
  const quick = quickScore(hostname, url, contextStr);
  if (quick >= 0.85) {
    await bumpStats(true);
    console.log(`[TruthLens] SMOKING GUN: Context/URL matched AI keywords`);
    return { score: quick, label: 'fake' };
  }

  try {
    const resp = await fetch(url, { mode: 'cors', credentials: 'omit' });
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    const blob = await resp.blob();

    // Fast-path #2: Digital Fingerprint (Metadata)
    const meta = await checkMetadata(blob);
    if (meta.found) {
      console.log(`[TruthLens] SMOKING GUN: Found metadata signature "${meta.name}"`);
      await bumpStats(true);
      return { score: 0.99, label: 'fake' };
    }

    const bitmap = await createImageBitmap(blob);

    // Two resolutions for different features
    const c224 = new OffscreenCanvas(224, 224);
    c224.getContext('2d').drawImage(bitmap, 0, 0, 224, 224);
    const px224 = c224.getContext('2d').getImageData(0, 0, 224, 224).data;

    const c64 = new OffscreenCanvas(64, 64);
    c64.getContext('2d').drawImage(bitmap, 0, 0, 64, 64);
    const px64 = c64.getContext('2d').getImageData(0, 0, 64, 64).data;

    const result = computeScore(px224, px64, quick);
    await bumpStats(result.label === 'fake');
    return result;

  } catch (e) {
    console.warn('[TruthLens] fetch/process error:', e.message);
    return { score: 0.05, label: 'real' };
  }
}

// ─── Pixel-level AI detection ─────────────────────────────────────────────────
//
// The single most reliable signal without ML:
//
//   MIN-BLOCK-NOISE (F1, weight 35%)
//   Look at the 10th percentile of 8×8 block standard deviations.
//   Real cameras add sensor grain even in smooth areas → min STD ≈ 3–8 units
//   AI generates mathematically perfect smooth areas → min STD ≈ 0.3–2 units
//   Works even for colourful/busy images because we look at the QUIETEST areas.
//
//   CHANNEL CORRELATION (F2, weight 20%)
//   AI channels generated jointly → unusually high R↔G↔B correlation (≥ 0.90)
//
//   TEXTURE ENTROPY (F3, weight 20%)
//   AI portrait skin is over-smooth → lower entropy at 64×64 scale
//
//   SKIN-TONE CLUSTER (F4, weight 15%)
//   AI faces have tight Cb/Cr cluster, real faces are varied
//
//   SATURATION UNIFORMITY (F5, weight 10%)
//   AI backgrounds/skin: very uniform saturation
//
function computeScore(px224, px64, domainBonus) {
  const minNoise = minBlockNoise(px224, 224);   // F1 — KEY feature
  const corr     = channelCorr(px224);           // F2
  const ent      = textureEntropy(px64);         // F3
  const skin     = skinCluster(px224);           // F4
  const satUni   = satUniformity(px224);         // F5

  // Bug #4 fix: normalise and apply calibrated thresholds
  // F1: minNoise < 2 → AI (smoothest 10% is nearly noiseless)
  //      real ≈ 3-8 intensity units; AI ≈ 0.3-2 units
  const f1 = clamp((3.5  - minNoise) / 3.0,  0, 1);

  // F2: corr > 0.88 → AI
  const f2 = clamp((corr  - 0.80) / 0.15,    0, 1);

  // F3: entropy < 0.72 → AI (smooth surfaces)
  const f3 = clamp((0.78  - ent)  / 0.25,    0, 1);

  // F4: tight skin cluster → AI
  const f4 = skin;

  // F5: saturation uniformity > 0.65 → AI
  const f5 = clamp((satUni - 0.55) / 0.30,   0, 1);

  // 0.08 baseline so unknown images default to UNVERIFIED, not REAL
  const raw   = 0.08 + 0.32*f1 + 0.20*f2 + 0.18*f3 + 0.14*f4 + 0.08*f5;
  const score = clamp(Math.max(raw, domainBonus), 0, 1);

  // Skeptical: only label REAL if all features are very low (score < 0.12)
  const label = score > 0.45 ? 'fake'
              : score > 0.12 ? 'unverified'
              : 'real';

  console.log(
    `[TruthLens] minNoise=${minNoise.toFixed(1)} corr=${corr.toFixed(2)} ent=${ent.toFixed(2)}` +
    ` f1=${f1.toFixed(2)} f2=${f2.toFixed(2)} f3=${f3.toFixed(2)} f4=${f4.toFixed(2)} f5=${f5.toFixed(2)}` +
    ` → ${(score*100).toFixed(1)}% (${label})`
  );
  return { score, label };
}

// ─── Feature extractors ───────────────────────────────────────────────────────

/**
 * 10th-percentile of 8×8 block luminance standard deviation.
 * Focuses on the QUIETEST regions — where real camera noise is still visible
 * but AI-generated images are perfectly smooth.
 */
function minBlockNoise(px, W) {
  const B = 8, H = W;
  const stds = [];
  for (let by = 0; by < H - B; by += B) {
    for (let bx = 0; bx < W - B; bx += B) {
      let sum = 0, sum2 = 0;
      for (let dy = 0; dy < B; dy++) {
        for (let dx = 0; dx < B; dx++) {
          const i = ((by + dy) * W + (bx + dx)) * 4;
          const l = 0.299 * px[i] + 0.587 * px[i+1] + 0.114 * px[i+2];
          sum += l; sum2 += l * l;
        }
      }
      const n = B * B, mu = sum / n;
      stds.push(Math.sqrt(Math.max(0, sum2 / n - mu * mu)));
    }
  }
  stds.sort((a, b) => a - b);
  return stds[Math.floor(stds.length * 0.10)] || 0;  // 10th percentile
}

function channelCorr(px) {
  const n = px.length / 4;
  let sR=0,sG=0,sB=0,sRG=0,sRB=0,sGB=0,sR2=0,sG2=0,sB2=0;
  for (let i=0; i<n; i++) {
    const r=px[i*4]/255, g=px[i*4+1]/255, b=px[i*4+2]/255;
    sR+=r; sG+=g; sB+=b; sRG+=r*g; sRB+=r*b; sGB+=g*b;
    sR2+=r*r; sG2+=g*g; sB2+=b*b;
  }
  const p = (sx,sy,sxy,sx2,sy2) => {
    const d = Math.sqrt((n*sx2-sx*sx)*(n*sy2-sy*sy));
    return d < 1e-9 ? 0 : (n*sxy - sx*sy) / d;
  };
  return (Math.abs(p(sR,sG,sRG,sR2,sG2)) + Math.abs(p(sR,sB,sRB,sR2,sB2)) + Math.abs(p(sG,sB,sGB,sG2,sB2))) / 3;
}

function textureEntropy(px) {
  const hist = new Float32Array(64), n = px.length / 4;
  for (let i=0; i<n; i++) {
    const l = 0.299*px[i*4] + 0.587*px[i*4+1] + 0.114*px[i*4+2];
    hist[Math.min(63, l >> 2)]++;
  }
  let e = 0;
  for (const v of hist) if (v > 0) { const p = v/n; e -= p * Math.log2(p); }
  return e / 6;
}

function skinCluster(px) {
  const n = px.length / 4;
  const cb = [], cr = [];
  for (let i=0; i<n; i++) {
    const r=px[i*4]/255, g=px[i*4+1]/255, b=px[i*4+2]/255;
    const Y=0.299*r+0.587*g+0.114*b;
    const Cb=-0.169*r-0.331*g+0.5*b+0.5;
    const Cr=0.5*r-0.419*g-0.081*b+0.5;
    if (Y>0.10 && Y<0.95 && Cb>0.37 && Cb<0.48 && Cr>0.51 && Cr<0.63) { cb.push(Cb); cr.push(Cr); }
  }
  if (cb.length < 80) return 0;
  const mCb = cb.reduce((a,v)=>a+v,0)/cb.length;
  const mCr = cr.reduce((a,v)=>a+v,0)/cr.length;
  const vCb = cb.reduce((a,v)=>a+(v-mCb)**2,0)/cb.length;
  const vCr = cr.reduce((a,v)=>a+(v-mCr)**2,0)/cr.length;
  return clamp((0.006 - (vCb+vCr)) / 0.005, 0, 1);
}

function satUniformity(px) {
  const n = px.length / 4;
  const sats = new Float32Array(n);
  for (let i=0; i<n; i++) {
    const r=px[i*4]/255, g=px[i*4+1]/255, b=px[i*4+2]/255;
    const mx=Math.max(r,g,b), mn=Math.min(r,g,b);
    sats[i] = mx < 1e-6 ? 0 : (mx - mn) / mx;
  }
  let sum = 0;
  for (const s of sats) sum += s;
  const mu = sum / n;
  let v = 0;
  for (const s of sats) v += (s - mu) ** 2;
  return clamp(1 - Math.sqrt(v / n) / 0.35, 0, 1);
}

function clamp(v, lo, hi) { return v < lo ? lo : v > hi ? hi : v; }
